### ISSUE TITLE
TypoScript - Prerequisites

### ISSUE THREAD

**Issue by reneroboter** [TYPO3-Documentation/TYPO3CMS-Tutorial-Typoscript45Minutes#17]
In the chapter prerequisites its says you should see under "backend", but I start to learn under typo3 7.6 and I only found "backend_layout".
Is there a mistake in the Docs or different table names between typo3 6 and typo3 7 ?

**Comment by Chrissitopher** [comment]
That setion on the one hand means the database tables pages (where the page records are) and tt_content (which contains all the different content elements). "Backend" on the other hand does not reference a database table, but it means the TYPO3 backend.

I hope this is more clear with b432a71dfe19b708432045d1449c974c01e88402
