### ISSUE TITLE
page.20.references.uid.data = tsfe:id

### ISSUE THREAD

**Issue by co-operate** [TYPO3-Documentation/TYPO3CMS-Tutorial-Typoscript45Minutes#18]
In chapter TypoScript Objects - Objects rendering content, the FILES example ist set to `uid = page:uid`. 

According to TSRef this should be either `uid.data = page:uid` (.data is currently missing), or even `uid.data = tsfe:id`, cf. https://docs.typo3.org/typo3cms/TyposcriptReference/7.6/ContentObjects/Files/#special-key-references

**Comment by fsuter** [comment]
Hmm, I don't see the error you mention. All examples I could find on that page were correct.

**Comment by co-operate** [comment]
@fsuter 
It's the FILES example on: https://docs.typo3.org/typo3cms/TyposcriptIn45MinutesTutorial/TypoScriptObjects/RenderingContent/Index.html
In line 6, the uid is set to `page:uid`. My understanding is that such a key:code pair can be gotten only through getText and thus requires stdWrap.data. Hence `uid.data = page:uid`?

**Comment by fsuter** [comment]
Ah, I see now. I had followed the link you posted to the TSref, and couldn't find any mistake there ;-)
